In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [2]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']
sentiment= np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[15, 16], [6, 19], [6, 3], [24, 28, 5], [6, 17, 18], [4, 16], [23, 17, 26], [10, 13], [10, 26], [3, 24]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[15, 16,  0,  0],
       [ 6, 19,  0,  0],
       [ 6,  3,  0,  0],
       [24, 28,  5,  0],
       [ 6, 17, 18,  0],
       [ 4, 16,  0,  0],
       [23, 17, 26,  0],
       [10, 13,  0,  0],
       [10, 26,  0,  0],
       [ 3, 24,  0,  0]])

In [5]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [6]:
x = padded_reviews
y = sentiment

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model.fit(x,y)



1/1 [==============================] - 1s 1s/step - loss: 0.6953 - accuracy: 0.5000


In [9]:
loss, acuracy = model.evaluate(x,y)
acuracy

1/1 [==============================] - 0s 327ms/step - loss: 0.6939 - accuracy: 0.5000


0.5

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[16]

array([-0.00909247,  0.00697018,  0.02713722,  0.02020523, -0.04626101],
      dtype=float32)

In [12]:
weights[5]

array([-0.0469389 , -0.02370968,  0.04827242, -0.02434579, -0.04413401],
      dtype=float32)